application: experian-services
version: 0-0-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  secure: optional
- url: /static
  static_dir: static
  secure: optional
- url: /cron.*
  script: main.app
  login: admin
  secure: always
- url: /tasks.*
  script: main.app
  login: admin
  secure: always
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  secure: optional
- url: .*
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "2.5.2"
